### ISSUE TITLE
Add support to Mac OS

### ISSUE THREAD

**Issue by pedromassango** [canewsin/flutter_desktop_launcher#1]
I want support to this version of the Flutter on Mac OS:

![Screen Shot 2019-04-01 at 10 10 39](https://user-images.githubusercontent.com/33294549/55471445-ae419380-5601-11e9-979f-ba3ff8f92c6d.png)

If you have not a Mac just tell me the steps, I will do it and then send a pull request!

**Comment by canewsin** [comment]
# Building on Mac OS
 - Tools 
    -  current version of Xcode
 - clone this repo from https://github.com/google/flutter-desktop-embedding.git
- after cloning repo appears like below
```
<parent dir>
  ├─ flutter (from https://github.com/flutter/flutter)
  └─ flutter-desktop-embedding (from https://github.com/google/flutter-desktop-embedding)
  ```
 - Alternately, you can place a .flutter_location_config file in the directory containing flutter-desktop-embedding, containing a path to the Flutter tree to use, if you prefer not to have the Flutter tree next to flutter-desktop-embedding.
- open this flutter-desktop-embedding/example/macos_fde in Xcode
- build and run that project

**Comment by canewsin** [comment]
@pedromassango after that post your results here

**Comment by canewsin** [comment]
@pedromassango any progress

**Comment by pedromassango** [comment]
Hi, sorry for delay. My computer just broke.

I tried it now and I am getting this error when running on Xcode:

![Screen Shot 2019-04-06 at 22 24 46](https://user-images.githubusercontent.com/33294549/55675476-f9d29680-58ba-11e9-9ad5-9691afec8815.png)

**Comment by mamnarock** [comment]
> Hi, sorry for delay. My computer just broke.
> 
> I tried it now and I am getting this error when running on Xcode:
> 
> ![Screen Shot 2019-04-06 at 22 24 46](https://user-images.githubusercontent.com/33294549/55675476-f9d29680-58ba-11e9-9ad5-9691afec8815.png)

This can be fixed with "product/clean build folder" and then run it again...

remember to have the "flutter" clone on the parent directory.

**Comment by pedromassango** [comment]
It keep showing me an error when trying to build the project after "product/clean build folder"

![Screen Shot 2019-04-07 at 18 48 47](https://user-images.githubusercontent.com/33294549/55687542-e7f9fd80-5965-11e9-9859-35c915fbff6b.png)

**Comment by mamnarock** [comment]
have you cloned the flutter project?

I had that same error when I did not have the flutter project.

```
<parent dir>
  ├─ flutter (from https://github.com/flutter/flutter)
  └─ flutter-desktop-embedding (from https://github.com/google/flutter-desktop-embedding)
```

**Comment by pedromassango** [comment]
I already have flutter  repository on my computer (in the parent directory)

**Comment by mamnarock** [comment]
> I already have flutter repository on my computer (in the parent directory)

well... see what means that error in the error log detail.

**Comment by pedromassango** [comment]
I'm downloading flutter repository again. What I need to do if the build succeed?

**Comment by pedromassango** [comment]
Ok. The build succeeded. It opened a Mac OS app. What I need to do next?

**Comment by canewsin** [comment]
@pedromassango did your app opened successfully

**Comment by canewsin** [comment]
if yes you can continue from this step on ReadMe file
 - Modify your main.dart add target platform to Fuchsia

go to this link https://github.com/canewsin/flutter_desktop_launcher#code-usage

If all goes with success create a pull request to this repo 

for more reference see this video https://www.youtube.com/watch?v=QFD2r4C3fHs

**Comment by pedromassango** [comment]
So my flutter project should be placed on the same directory as the flutter-desktop-embedding folder?

**Comment by PramUkesh** [comment]
You Compiled the Executables Now so you have gather those files Flutter.app and build-run.sh(file name may be different i dont remember that) and paste those in your project folder 
Modify your app as required go to this https://github.com/canewsin/flutter_desktop_launcher#code-usage
now your app runs as desktop app

**Comment by pedromassango** [comment]
Where I can find those files? I'm currently looking on macos_fde and example folder and I can't find it

**Comment by PramUkesh** [comment]
files found can be found at flutter-desktop-embedding>example>macosfde>

**Comment by pedromassango** [comment]
@PramUkesh can you help me with doing this by entering on my pc? maybe via AnyDesk

**Comment by pedromassango** [comment]
This is my macos_fde after build successfully the project with xCode

![Screen Shot 2019-04-13 at 18 04 02](https://user-images.githubusercontent.com/33294549/56082923-8d095000-5e16-11e9-9842-3503920397dd.png)

**Comment by canewsin** [comment]
@pedromassango
I will try 
Whats your UTC time zone
I am from india utc +5:30

**Comment by canewsin** [comment]
Open that folder macos fde in xcode and build and run that target now i will work now

one more thing is @PramUkesh is my personal account so dont confuse as different person both @canewsin and above belongs to me you can mention any name

**Comment by pedromassango** [comment]
Ok. My time zone is UTC +1

22:42 right now

**Comment by pedromassango** [comment]
Yes, I already run the macos fde project, then I copy the Flutter Embeder.app located at Debug folder to my flutter project then I followed the steps from the readme but it is launching the Counter Sample App

**Comment by canewsin** [comment]
after copying 
run 
> flutter build bundle 

in your root project it will load your src to app
and then
You have to connect your app through vscode debug (see details in ReadMe.md)

**Comment by canewsin** [comment]
@pedromassango do you have any c/c++ background
i need some help with other issue #2

**Comment by pedromassango** [comment]
@canewsin I don't,

I still can't get it working on my project

**Comment by canewsin** [comment]
@pedromassango  where are you stuck

**Comment by canewsin** [comment]
@pedromassango  new version flutter_desktop_embedding is released try with that version

**Comment by canewsin** [comment]
Closing this as old issue, open new issue if it still happens.
