### ISSUE TITLE
start flutter desktop on linux

### ISSUE THREAD

**Issue by cyberiumcodes** [canewsin/flutter_desktop_launcher#3]
[ERROR:flutter/shell/platform/embedder/embedder.cc(379)] Not running in AOT mode but could not resolve the kernel binary.
[ERROR:flutter/shell/platform/embedder/embedder.cc(47)] Returning error 'kInvalidArguments' (2) from Flutter Embedder API call to 'LogEmbedderError'. Origin: ../../flutter/shell/platform/embedder/embedder.cc:381
Failed to start Flutter engine: error 2
Failed to create window.

**Comment by canewsin** [comment]
This log is not enough to evalute the issue, do you follow the guide correctly ?

post your 
`flutter doctor -v`

**Comment by cyberiumcodes** [comment]
Flutter (Channel stable, v1.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.2.1 at /home/cyberiumcodes/development/flutter
    • Framework revision 8661d8aecd (8 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/cyberiumcodes/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /snap/android-studio/73/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /snap/android-studio/73/android-studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at /snap/intellij-idea-community/137
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.88

**Comment by canewsin** [comment]
I checked now it works flawlessly without any problem

Brief Steps:
Download the linux launcher in folder v1.2.1 go to below link
https://github.com/canewsin/flutter_desktop_launcher/tree/master/v1.2.1

extract all the files to your project 

open terminal > run 
`flutter build bundle`

after that run
`./flutter_desktop`

**Comment by cyberiumcodes** [comment]
done all that,maybe mine distribution of OS missing something...Thanks anyway for your efford to help

**Comment by canewsin** [comment]
@cyberiumcodes could you take a gif image or video of that so i can get idea where you had issue

**Comment by averrin** [comment]
Same error here.

```
>>  flutter doctor -v
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.2.1 at /opt/flutter
    • Framework revision 8661d8aecd (10 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/averrin/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/averrin/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[!] Android Studio (version 3.4)
    • Android Studio at /home/averrin/Downloads/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

>>./flutter_desktop
GLFW error 65544: Linux: Failed to watch for joystick connections in /dev/input: No space left on device
[ERROR:flutter/shell/platform/embedder/embedder.cc(379)] Not running in AOT mode but could not resolve the kernel binary.
[ERROR:flutter/shell/platform/embedder/embedder.cc(47)] Returning error 'kInvalidArguments' (2) from Flutter Embedder API call to 'LogEmbedderError'. Origin: ../../flutter/shell/platform/embedder/embedder.cc:381
Failed to start Flutter engine: error 2
Failed to create window.
```

So there is nothing to record for gif its just screen blink.

OS: Manjaro. Flutter versions: 1.2.1 from AUR

**Comment by canewsin** [comment]
@averrin @cyberiumcodes 
New Version Arrived  I will Upload once i compiled it and tested on my side it works, once i fully confirmed i will upload, it may take 24 hours from now

**Comment by canewsin** [comment]
@cyberiumcodes @averrin 
New Version Released Try with those currently released windows version, will release Linux version in an hour or two

**Comment by yossefEl** [comment]
I have the same problem 
[ERROR:flutter/shell/platform/embedder/embedder.cc(379)] Not running in AOT mode but could not resolve the kernel binary.
[ERROR:flutter/shell/platform/embedder/embedder.cc(47)] Returning error 'kInvalidArguments' (2) from Flutter Embedder API call to 'LogEmbedderError'. Origin: ../../flutter/shell/platform/embedder/embedder.cc:381
Failed to start Flutter engine: error 2
Failed to create window.

**Comment by canewsin** [comment]
Closing this as old issue, open new issue if it still happens.
