### ISSUE TITLE
Win10 FlutterOpenGLRendererConfig error

### ISSUE THREAD

**Issue by dogukankse** [canewsin/flutter_desktop_launcher#4]
flutter_desktop.exe trows this error: 

> [ERROR:c:\b\s\w\ir\k\src\flutter\shell\platform\embedder\embedder_surface_gl.cc(95)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
[ERROR:c:\b\s\w\ir\k\src\flutter\shell\platform\embedder\embedder_surface_gl.cc(95)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
flutter: Observatory listening on http://127.0.0.1:65225/

and my launch.json looks like this:
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Flutter",
            "request": "launch",
            "type": "dart"
        },
        {
            "name": "Flutter Desktop",
            "request": "attach",
            "deviceId": "flutter-tester",
            "observatoryUri": "http://127.0.0.1:65190",
            "type": "dart"
        }
    ]
}
`

**Comment by canewsin** [comment]
Error are common project is in early stage
And another thing is Observatory Uri given in Console must match with launch.json file
every time it changes with new lauch so take note of it while building
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Flutter Desktop",
      "request": "attach",
      "deviceId": "flutter-tester",
      "observatoryUri": "http://127.0.0.1:65225/",
      "type": "dart"
    }
  ]
}
```

**Comment by JAICHANGPARK** [comment]
```terminal:
[ERROR:c:\b\s\w\ir\k\src\flutter\shell\platform\embedder\embedder_surface_gl.cc(95)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
[ERROR:c:\b\s\w\ir\k\src\flutter\shell\platform\embedder\embedder_surface_gl.cc(95)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
[ERROR:c:\b\s\w\ir\k\src\flutter\shell\common\shell.cc(184)] Dart Error: Can't load Kernel binary: Invalid kernel binary format version.
[ERROR:c:\b\s\w\ir\k\src\flutter\shell\common\engine.cc(176)] Could not prepare to run the isolate.
[ERROR:c:\b\s\w\ir\k\src\flutter\shell\common\engine.cc(123)] Engine not prepare and launch ifsloultatte.
er: Observatory listening on http://127.0.0.1:56260/
[ERROR:c:\b\s\w\ir\k\src\flutter\shell\platform\embedder\embedder_engine.cc(69)] Could not launch the engine with configuration.

```

> flutter attach --device-id=flutter-tester --debug-port=56260

I had some error

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)

.vscode/launch.json 

```
{
    "version": "0.2.0",
    "configurations": [
      {
        "name": "Flutter Desktop",
        "request": "attach",
        "deviceId": "flutter-tester",
        "observatoryUri": "http://127.0.0.1:56260/",
        "type": "dart"
      }
    ]
  }
```

**Comment by canewsin** [comment]
Did You Run `flutter build bundle` ?
@dogukankse @JAICHANGPARK 

Try with new version it may work without errors

**Comment by dogukankse** [comment]
There is no error for me now

**Comment by canewsin** [comment]
Closing this as old issue, open new issue if it still happens.
