### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by cezar-pereira** [canewsin/flutter_desktop_launcher#6]
flutter: Observatory listening on http://127.0.0.1:49494/
[ERROR:flutter/shell/common/shell.cc(186)] Dart Error: Can't load Kernel binary: Invalid kernel binary format version.
[ERROR:flutter/shell/common/engine.cc(176)] Could not prepare to run the isolate.
[ERROR:flutter/shell/common/engine.cc(123)] Engine not prepare and launch isolate.
[ERROR:flutter/shell/platform/embedder/embedder_engine.cc(61)] Could not launch the engine with configuration.

flutter version Flutter 1.7.8

**Comment by canewsin** [comment]
Closing this as old issue, open new issue if it still happens.
